# **Introduction to SVD**

It In this notebook, you will practice your understanding of SVD by applying it to several matrices and exploring the result.

## **SVD: Theoretical Reminder**

Singular Value Decomposition (SVD) is a highlight of Linear Algebra. It allows one to decompose *any* rectangular matrix $A$ into a product of three matrices, namely **orthogonal** matrices $U$ and $V$ and a **diagonal** matrix $\Sigma$ as follows:

<center>$A = U\Sigma V^T$</center>

Such a decomposition makes subsequent computations easier and is important for many applications.

The diagonal values $\sigma_{i}$ in the $\Sigma$ matrix are known as the singular values of the original matrix $A$, while the columns of the $U$ and $V$ matrices, $u_i$'s and $v_i$'s, are left anf right singular vectors of $A$ respectively.

From the decomposition above it follows that the following relationship should hold between the singular values and the singular vectors:

<center>$Av_i = \sigma_i u_i$</center>

But how do we find those $u$'s, $v$'s and $\sigma$'s?

It turns out that the left singular vectors $u_1, ..., u_r$ are actually the eigenvectors of $AA^T$ that correspond to its non-zero eigenvalues, while the right singular vectors $v1, ..., v_r$ are the eigenvectors corresponding to the non-zero eigenvaluesof $A^TA$.

Finally, $A$'s singular values  $\sigma_i^2$ are the non-zero eigenvalues of both $A^TA$ and $AA^T$ *(see the lecture notes for a proof of why they are the same)*.

## **SVD in Action: Toy Example**

Luckily, SVD is already implemented in Python, and you will not need re-implement it from scratch ourselves.

Instead, let's define a toy matrix, decompose it with a built-in function and carefully explore the result.

**Run the cells below one-by-one, accasionally filling in the code where needed.**

In [1]:
import numpy as np

In [2]:
A = np.array([[3,4,3],
              [1,2,3]])

Now, apply SVD to the data we've just loaded.

*Hint:* The SVD can be calculated by calling the [$\texttt{svd()}$](https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html) function from the $\texttt{linalg}$ module of the $\texttt{numpy}$ library.



In [19]:
# Your code here
U, S, V = np.linalg.svd(A, full_matrices=False)

Let's explore the output of the function.

How many singular values does $A$ have?

In [20]:
# Your code here
len(S)

2

What are the dimensions of the matrices $U$ and $V$.

In [21]:
# Your code here
U.shape, V.shape

((2, 2), (3, 3))

Now, double-check that the decomposition actually works, i.e. check that $A = U\Sigma V^T$:

In [23]:
# Your code here
np.allclose(A, np.dot(U * S, V.T)) # its taken from: numpy.linalg.svd examples

ValueError: shapes (2,) and (3,3) not aligned: 2 (dim 0) != 3 (dim 0)

We've said before that the column vectors of the matrices $U$ and $V$ are the eigenvectors of $AA^T$ and $A^TA$ respectively, while $\sigma_i^2$ are the corresponding eigenvalues. Double-check that that's indeed the case.

In [10]:
# Your code here
# Compute AA^T
AAT = np.dot(A, A.T)

# Compute A^TA
ATA = np.dot(A.T, A)
# Eigenvalues and eigenvectors
eigenvalues_U, eigenvectors_U = np.linalg.eig(AAT)
eigenvalues_V, eigenvectors_V = np.linalg.eig(ATA)

# Check that the eigenvectors match U and V (normalized)
np.allclose(np.sort(eigenvectors_U, axis=1), U)
np.allclose(np.sort(eigenvectors_V, axis=1), V)



ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [18]:
np.sort(eigenvectors_U, axis=1), U

(array([[-0.52573111,  0.85065081],
        [ 0.52573111,  0.85065081]]),
 array([[-0.85065081, -0.52573111],
        [-0.52573111,  0.85065081]]))

In [46]:
U, AAT

(array([[-0.85065081, -0.52573111],
        [-0.52573111,  0.85065081]]),
 array([[34, 20],
        [20, 14]]))

Double-chek that $U$ and $V$ are orthogonal matrices (e.g., show that $UU^T = U^TU = E$)

In [ ]:
# Your code here


Finally, check that the relationship between the estimated singular vectors and singular values of $A$ is as follows: $Av_i = \sigma_i u_i$.

In [ ]:
# Your code here


## **SVD on the Iris Dataset**

Now, we'll apply SVD on the famous iris dataset.


In [ ]:
from sklearn.datasets import load_iris
from sklearn.decomposition import TruncatedSVD

iris = load_iris()
A = iris.data

Let's take a look at the first 10 examples:

In [ ]:
A[:10]

Now, apply SVD to the dataset:

In [ ]:
# Your code here


Explore the dimensions of the matrices $U$ and $V$ and the number of singular values of the data matrix, $r$.

In [ ]:
# Your code here


"Trim" the matrices $U$ and $V$ returned by $\texttt{np.svd()}$ to get rid of redundant dimensions.

You should get $A_{m\times n} = U_{m\times r}\Sigma_{r\times r} V_{n\times r}^T$, where $r$ is the number of singular values of the data matrix $A$.

In [ ]:
# Your code here


Imagine that we want to use only two factors in the latent representation of the data. How would the approximated data look like?

In [ ]:
# Your code here
