1. (2 points) Given a vector a and a set of vectors X = x1, ..., xm, we say that xi
is the nearest neighbor
of a if it’s the closest vector to a from the set X. In ML, the idea of the nearest neighbour and
its generalisation, k-nearest neighbours, is used for solving classification and regression problems (see
k-nearest neighbours algorithm).
Find the nearest neighbour of a = [3, 1, 4] from the set of vectors x1, ..., x4 below.

    'x1': np.array([4, 3, 6]),
    'x2': np.array([3, 1, 9]),
    'x3': np.array([1, 4, 10]),
    'x4': np.array([3, 4, 0])

If there is more than one nearest neighbour, mark all of them. Use
(a) (1 point) Euclidean distance

In [2]:
import numpy as np

In [3]:
import numpy as np

# Define the vectors
a = np.array([3, 1, 4])
X = {
    'x1': np.array([4, 3, 6]),
    'x2': np.array([3, 1, 9]),
    'x3': np.array([1, 4, 10]),
    'x4': np.array([3, 4, 0])
}



In [4]:
# (a) Find the nearest neighbor using Euclidean distance
def euclidean_distance(a, x):
    return np.linalg.norm(a - x)

In [5]:

# 
euclidean_distances = {key: euclidean_distance(a, vec) for key, vec in X.items()}
print(f"calculated the distances{euclidean_distances}")
print('answer:')
nearest_neighbor_euclidean = min(euclidean_distances, key=euclidean_distances.get)
nearest_distance_euclidean = euclidean_distances[nearest_neighbor_euclidean]

print("Euclidean Distance:")
print(f"Nearest Neighbor is {nearest_neighbor_euclidean} (Distance = {nearest_distance_euclidean})")


calculated the distances{'x1': 3.0, 'x2': 5.0, 'x3': 7.0, 'x4': 5.0}
answer:
Euclidean Distance:
Nearest Neighbor is x1 (Distance = 3.0)


In [6]:

# (b) Find the nearest neighbor using Cosine similarity
def cosine_similarity(a, x):
    return np.dot(a, x) / (np.linalg.norm(a) * np.linalg.norm(x))

cosine_similarities = {key: cosine_similarity(a, vec) for key, vec in X.items()}
nearest_neighbor_cosine = max(cosine_similarities, key=cosine_similarities.get)
nearest_similarity_cosine = cosine_similarities[nearest_neighbor_cosine]

print("\nCosine Similarity:")
print(f"Nearest Neighbor: {nearest_neighbor_cosine} (Similarity = {nearest_similarity_cosine})")


Cosine Similarity:
Nearest Neighbor: x1 (Similarity = 0.9792938238560597)


(2 points) Consider a linear classifier with the following separating hyperplane:
x1 + x2 − x3 + x4 − x5 = 2
According to this classifier, which class labels will be assigned to the examples (a) - (e)?

In [32]:
examples = {
    'a': np.array([1, 0, 1, 0, 0]),
    'b': np.array([0, 1, 1, 0, 1]),
    'c': np.array([1, 1, 1, 1, 1]),
    'd': np.array([2, 0, 1, 0, 1]),
    'e': np.array([2, 2, 0, 0, 0]),
}

# Define the separating hyperplane function
def classify(example):
    # Compute the value of the hyperplane equation
    hyperplane_value = example[0] + example[1] - example[2] + example[3] - example[4]
    
    # Classify based on the hyperplane value
    if hyperplane_value >= 2:
        return 1  # Class 1
    else:
        return 0  # Class 0

# Classify each example
class_labels = {label: classify(example) for label, example in examples.items()}

# Output the results
for label, class_label in class_labels.items():
    print(f'Example {label} is classified as class {class_label}.')

Example a is classified as class 0.
Example b is classified as class 0.
Example c is classified as class 0.
Example d is classified as class 0.
Example e is classified as class 1.


(1 point) Consider vectors v1, v2, v3 and v4 defined below:

What is the dimensionality of the subspace V = span{v1, v2, v3, v4} spanned by those vectors?

In [53]:
# Define the vectors as columns of a matrix
v1 = np.array([[0], [1], [1], [1]])
v2 = np.array([[1], [2], [0], [3]])
v3 = np.array([[2], [4], [1], [3]])
v4 = np.array([[1], [2], [1], [0]])

# Unit the vectors into a single matrix
A = np.hstack((v1, v2, v3, v4))

# Perform Singular Value Decomposition (SVD)
U, S, Vt = np.linalg.svd(A)

# The rank of the matrix corresponds to the number of non-zero singular values
rank = np.sum(S > 1e-10)  # Use a small threshold to consider numerical precision

print(f"The dimensionality of the subspace V is: {rank}")

The dimensionality of the subspace V is: 3


(3 points) Consider two sets of vectors, B and S:

In [49]:
# Define the vectors in basis B
B = np.array([
    [1, 2, 1],
    [2, 3, 3],
    [3, 8, 2]
]).T  # Transpose to get vectors as columns

# Define the vectors in basis S
S = np.array([
    [3, 5, 1],
    [5, 14, 9],
    [8, 13, 2]
]).T  # Transpose to get vectors as columns

# In order to find the transition matrix A_B->S, we need to solve the equation
# B * x = S for x, where x will be the coefficients we are looking for.
# We can find x by computing the inverse of B, provided B is invertible.

# Compute the inverse of B
B_inv = np.linalg.inv(B)

# Compute the transition matrix from B to S
A_B_to_S = B_inv @ S

# Display the transition matrix
print("Transition matrix A_B->S:")
print(A_B_to_S)

Transition matrix A_B->S:
[[ 22. -43.  65.]
 [ -5.  12. -15.]
 [ -3.   8.  -9.]]


In [56]:
pwd


'/home/andrei/PycharmProjects/Girafe/math/homework'